src/demo/demo.js

Make demo work with the current master branch of the its-ws-server and its-gae.

refactor(demo): make demo work

---

src/demo/demo.js
src/demo/index.html

Remove functionality hiding so all tabs are visible.

feat(demo): remove functionality hiding

---

src/demo/demo.js

Change ordering of switching tabs so all tabs get switched off first
before a new one is switched on.

style(demo): change ordering of tab switching

---

src/demo/demo.js

Various fixes for demo bugs and inefficiencies

Demo fixes

---

src/demo/demo.js

Use promises of the new SDK in streaming.
Resolve #10

refactor(demo): use promises

---

src/demo/demo.js

Use basicauth and request an oauth2 token.

feat(oauth2): get oauth2 token

---

src/components/audio-components-segmentplayer.js
src/components/audio-components.css
src/components/audio-components.js

Simplify code

---

src/components/audio-components-segmentplayer.js
src/components/audio-components.js
src/recordingDemo/index.html
src/recordingDemo/recordingDemo.css
src/recordingDemo/recordingDemo.js
webpack.config.js

Simple recording demo

---

src/recordingDemo/recordingDemo.js

Clarify what 'dummy' is and where its used.

refactor(recordingdemo): clarify variables

---

package.json
src/components/audio-components.js
src/recordingDemo/recordingDemo.js
webpack.config.js

Use ES6 babelifier and remove some old code.

Es6 babel and fix

---

package.json

chore(package): add missing dependency

---

src/recordingDemo/recordingDemo.js

feat(recordingdemo): set download link

---

.travis.yml
src/components/audio-components-segmentplayer.js
src/demo/demo.js
src/recordingDemo/recordingDemo.js

Add travis and fix eslint issues

Add travis

---

src/recordingDemo/index.html
src/recordingDemo/recordingDemo.js

Remove second player and segmentplayer.

refactor(recordingdemo): simplify demo

---

src/analysisDemo/analysisDemo.js
src/analysisDemo/index.html
src/components/textual-components.js
webpack.config.js

Add demo showing analysis and result processing.
I don't know if I show the alignment and analysis results correctly. It's a bit vague what is supposed to happen.
Resolve #19

feat(analysisdemo): add demo

---

package.json
src/audioReferenceDemo/audioReferenceDemo.js
src/audioReferenceDemo/index.html
src/components/audio-components-segmentplayer.js
src/components/audio-components.js
webpack.config.js

Add wavesurfer and audio reference demo.
Resolve #32, resolve #16

Audio reference

---

src/analysisDemo/analysisDemo.js
src/recordingDemo/recordingDemo.js

Fix demos to work with itslanguage 0.2.1.

fix(demos): fix for 0.2.1

---

.gitignore

Don't ignore dist folder or it won't be committed to the gh-pages branch.

chore(gitignore): remove dist ignore

---

src/analysisDemo/index.html
src/audioReferenceDemo/index.html
src/components/audio-components-segmentplayer.js
src/components/audio-components.css
src/components/audio-components.js
src/components/textual-components.css
src/components/textual-components.js
src/demo/index.html
src/recordingDemo/index.html

Prefix every custom class we use in the demos with 'itslanguage-'
Solves #41

refactor: prefix css with itslanguage-

---

src/recognitionDemo/index.html

Fix title.
It was just for this one.

fix(recognition): fix title

---

deploy.sh

Fix deploy to save the index.html from the existing branch
before pushing the new one. Else it will destroy the file.
This should fix it.

chore(deploy): fix deploy

---

deploy.sh
package.json

Fix build and deploy

---

deploy.sh

Get index file from the gh-pages branch to save it.

chore(deploy): get index

---

src/recognitionDemo/recognitionDemo.js

Throw result when nothing is recognized instead of a new error.

fix(recognition): throw result

---

src/analysisDemo/analysisDemo.js
src/components/audio-components.js
src/recognitionDemo/recognitionDemo.js
src/recordingDemo/recordingDemo.js

Fixes to match new itslanguage version

Fix for new its

---

package.json
src/analysisDemo/analysisDemo.js
src/recognitionDemo/recognitionDemo.js
src/recordingDemo/recordingDemo.js
src/settings/settings.json

Update demos for latest itslanguage sdk version 2.0.0

Latest itsl

---

README.md

docs(readme): add link to github pages demo

---

src/recordingDemo/recordingDemo.js
src/settings/settings.json

fix: use student user and user authentication for recording demo
